[project]
name = "raphael"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "subrotokumar", email = "subrotokumar@outlook.in" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=3.8.0",
]

[project.scripts]
raphael = "raphael:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
